import {VoiceEngine} from './voice-engine.js?v=5';
import {Playback} from './playback.js?v=5';
import {VisualEngine} from './visual-engine.js?v=5';
import {COURSE,buildLesson} from './course-engine.js?v=5';
import {buildCustom} from './session-builder.js?v=5';
import {exportWav,exportMp3,download} from './export-engine.js?v=5';
import {exportVideo} from './video-export.js?v=5';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const voice=new VoiceEngine();const playback=new Playback(voice),visual=new VisualEngine($('#visualCanvas'));
voice.init().catch(()=>{});
let currentLesson=Number(localStorage.getItem('cwStudio.currentLesson')||1),timeline=null,wizardStep=1,selectedModes=new Set(['familiarization','recognition']),selectedContents=new Set(['letters']),selectedDuration=900;
const completed=new Set(JSON.parse(localStorage.getItem('cwStudio.completedLessons')||'[]'));

function fmt(s){s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function drawLoop(t=0){visual.draw(t,timeline);$('#timeLabel').textContent=`${fmt(t)} / ${fmt(timeline?.duration||0)}`}
function meta(){return {title:timeline?.meta?.title||'CW Studio Session',comment:`${timeline?.meta?.kind==='course'?'Learn CW lesson':'Custom practice session'} · Generated by ZP5DXS with Morse Practice CW Studio`}}

async function loadLesson(n){currentLesson=Math.max(1,Math.min(20,n));localStorage.setItem('cwStudio.currentLesson',currentLesson);$('#statusLabel').textContent=`LESSON ${String(currentLesson).padStart(2,'0')}`;$('#currentLessonLabel').textContent=`Lesson ${String(currentLesson).padStart(2,'0')}`;timeline=await buildLesson(currentLesson,{lang:$('#languageSelect').value,gender:$('#voiceSelect').value,voice});renderLessons();drawLoop(0)}

function renderLessons(){
  $('#lessonGrid').innerHTML=COURSE.map(l=>`<article class="lesson ${l.lesson===currentLesson?'current':''} ${completed.has(l.lesson)?'completed':''}" data-lesson="${l.lesson}"><div class="lesson-top"><div class="n">LESSON ${String(l.lesson).padStart(2,'0')}</div><span class="lesson-check">${completed.has(l.lesson)?'✓':''}</span></div><h3>${l.newItems.length?l.newItems.join(' · '):l.focus}</h3><p>${l.focus}<br>${l.charWpm} WPM · ${l.effectiveWpm} effective</p></article>`).join('');
  $$('.lesson').forEach(el=>el.onclick=()=>loadLesson(Number(el.dataset.lesson)));
  $('#prevLessonBtn').disabled=currentLesson===1;$('#nextLessonBtn').disabled=currentLesson===20;
  $('#courseProgressText').textContent=`${completed.size} / 20 completed`;$('#courseProgressBar').style.width=`${completed.size/20*100}%`
}
function completeCurrent(){if(timeline?.meta?.kind!=='course')return;completed.add(currentLesson);localStorage.setItem('cwStudio.completedLessons',JSON.stringify([...completed].sort((a,b)=>a-b)));renderLessons()}

$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.panel').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab+'Panel').classList.add('active')});
$('#prevLessonBtn').onclick=()=>loadLesson(currentLesson-1);$('#nextLessonBtn').onclick=()=>loadLesson(currentLesson+1);
$('#languageSelect').onchange=()=>timeline?.meta?.kind==='course'&&loadLesson(currentLesson);$('#voiceSelect').onchange=()=>timeline?.meta?.kind==='course'&&loadLesson(currentLesson);

const bonuses=[['100 Common Words','Build word-level recognition'],['100 Real Callsigns','Real-world callsign retention'],['100 Radio Words','Operational vocabulary'],['100 Numbers','Numbers in radio contexts'],['100 CW Abbreviations','Common operating shorthand'],['QSO Head Copy','Progressive complete exchanges'],['Endless Head Copy','Continuous listening']];
$('#bonusGrid').innerHTML=bonuses.map(x=>`<article class="bonus"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');

const CONTENTS=[['letters','Letters'],['numbers','Numbers'],['alnum','Letters + Numbers'],['punctuation','Punctuation'],['prosigns','Prosigns'],['abbreviations','CW Abbreviations'],['callsigns','Callsigns'],['prefixes','Prefixes'],['rst','RST'],['qso','QSO'],['words','Words'],['custom','Custom Text']];
function renderContentChoices(){
  const fam=selectedModes.has('familiarization'),onlyFam=fam&&selectedModes.size===1;const allowed=onlyFam?new Set(['letters','numbers']):new Set(CONTENTS.map(x=>x[0]));
  if(onlyFam)for(const x of [...selectedContents])if(!allowed.has(x))selectedContents.delete(x);
  if(!selectedContents.size)selectedContents.add('letters');
  $('#contentChoices').innerHTML=CONTENTS.filter(([id])=>allowed.has(id)).map(([id,label])=>`<button class="choice compact ${selectedContents.has(id)?'selected':''}" data-content="${id}"><strong>${label}</strong></button>`).join('');
  $$('[data-content]').forEach(b=>b.onclick=()=>{const id=b.dataset.content;if(selectedContents.has(id))selectedContents.delete(id);else selectedContents.add(id);if(!selectedContents.size)selectedContents.add(id);renderContentChoices();$('#customTextWrap').classList.toggle('hidden',!selectedContents.has('custom'))});
  $('#customTextWrap').classList.toggle('hidden',!selectedContents.has('custom'))
}
$$('[data-mode]').forEach(b=>b.onclick=()=>{const id=b.dataset.mode;if(selectedModes.has(id))selectedModes.delete(id);else selectedModes.add(id);if(!selectedModes.size)selectedModes.add(id);$$('[data-mode]').forEach(x=>x.classList.toggle('selected',selectedModes.has(x.dataset.mode)));renderContentChoices()});
renderContentChoices();

function setWizard(n){wizardStep=Math.max(1,Math.min(4,n));$$('.wizard-step').forEach(x=>x.classList.toggle('active',+x.dataset.step===wizardStep));$$('.wizard-panel').forEach(x=>x.classList.toggle('active',+x.dataset.wizardPanel===wizardStep));$('#wizardBack').style.visibility=wizardStep===1?'hidden':'visible';$('#wizardNext').classList.toggle('hidden',wizardStep===4);$('#buildSessionBtn').classList.toggle('hidden',wizardStep!==4)}
$$('.wizard-step').forEach(b=>b.onclick=()=>setWizard(+b.dataset.step));$('#wizardBack').onclick=()=>setWizard(wizardStep-1);$('#wizardNext').onclick=()=>setWizard(wizardStep+1);setWizard(1);
['wpm','eff','tone','delay'].forEach(k=>{$(`#${k}Range`).oninput=e=>$(`#${k}Value`).textContent=e.target.value});
$('#advancedToggle').onclick=()=>{$('#advancedOptions').classList.toggle('hidden');$('#advancedToggle').textContent=$('#advancedOptions').classList.contains('hidden')?'Advanced ▾':'Advanced ▴'};
$$('.duration-choice').forEach(b=>b.onclick=()=>{selectedDuration=+b.dataset.duration;$$('.duration-choice').forEach(x=>x.classList.toggle('selected',x===b))});

$('#buildSessionBtn').onclick=()=>{timeline=buildCustom({familiarization:selectedModes.has('familiarization'),recognition:selectedModes.has('recognition'),marathon:selectedModes.has('marathon'),contents:[...selectedContents],customText:$('#customText').value,wpm:+$('#wpmRange').value,eff:+$('#effRange').value,tone:+$('#toneRange').value,delay:+$('#delayRange').value,variableRecognition:$('#variableRecognition').checked,toneVariation:$('#toneVariation').checked,duration:selectedDuration,seed:$('#seedInput').value});$('#statusLabel').textContent='CUSTOM SESSION';drawLoop(0)};

async function play(limit=null){await playback.play(timeline,{lang:$('#languageSelect').value,gender:$('#voiceSelect').value,tone:+$('#toneRange').value,limit,onTick:(t,a)=>{visual.setAnalyser(a);drawLoop(t)},onEnd:()=>{drawLoop(limit||timeline.duration);if(!limit)completeCurrent()}})}
$('#playBtn').onclick=()=>play();$('#previewBtn').onclick=()=>play(30);$('#stopBtn').onclick=()=>{playback.stop();drawLoop(0)};
$('#wavBtn').onclick=async()=>{const b=await exportWav(timeline,voice,{lang:$('#languageSelect').value,gender:$('#voiceSelect').value,tone:+$('#toneRange').value},meta());download(b,`${timeline?.meta?.kind==='course'?`learn-cw-${String(currentLesson).padStart(2,'0')}`:'cw-studio-session'}.wav`)};
$('#mp3Btn').onclick=async()=>{const b=await exportMp3(timeline,voice,{lang:$('#languageSelect').value,gender:$('#voiceSelect').value,tone:+$('#toneRange').value},meta());download(b,`${timeline?.meta?.kind==='course'?`learn-cw-${String(currentLesson).padStart(2,'0')}`:'cw-studio-session'}.mp3`)};
$('#videoBtn').onclick=async()=>{const btn=$('#videoBtn'),old=btn.textContent;btn.disabled=true;try{const b=await exportVideo(timeline,voice,visual,{lang:$('#languageSelect').value,gender:$('#voiceSelect').value,tone:+$('#toneRange').value,onProgress:p=>btn.textContent=`Video ${Math.round(p*100)}%`});download(b,`${timeline?.meta?.kind==='course'?`learn-cw-${String(currentLesson).padStart(2,'0')}`:'cw-studio-session'}.webm`)}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent=old;drawLoop(0)}};

renderLessons();
$('#assetStatus').textContent='Voice resolver ready · audio loads on demand';
loadLesson(currentLesson).then(()=>{const r=voice.roots();if(r.core||r.course){$('#assetStatus').textContent=`Audio ready${r.core?` · Core: ${r.core}`:''}${r.course?` · Course: ${r.course}`:''}`;$('#assetStatus').classList.remove('warning')}}).catch(err=>{console.error(err);$('#assetStatus').textContent='Lesson loaded with audio fallback · open console only if a voice clip is missing';});
