import {VoiceEngine} from './voice-engine.js';import {Playback} from './playback.js';import {VisualEngine} from './visual-engine.js';import {COURSE,buildLesson} from './course-engine.js';import {buildCustom} from './session-builder.js';import {exportWav,exportMp3,download} from './export-engine.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const voice=new VoiceEngine();await voice.init();const playback=new Playback(voice),visual=new VisualEngine($('#visualCanvas'));let timeline=buildLesson(1,'es'),raf;
function fmt(s){s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function drawLoop(t=0){visual.draw(t,timeline);$('#timeLabel').textContent=`${fmt(t)} / ${fmt(timeline.duration)}`}
drawLoop(0);
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.panel').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab+'Panel').classList.add('active')});
$('#lessonGrid').innerHTML=COURSE.map(l=>`<article class="lesson" data-lesson="${l.lesson}"><div class="n">LESSON ${String(l.lesson).padStart(2,'0')} · ${l.phase}</div><h3>${l.newItems.length?l.newItems.join(' · '):l.focus}</h3><p>${l.focus}<br>${l.charWpm} WPM · ${l.effectiveWpm} effective</p></article>`).join('');
$$('.lesson').forEach(el=>el.onclick=()=>{timeline=buildLesson(Number(el.dataset.lesson),$('#languageSelect').value);$('#statusLabel').textContent=`LESSON ${el.dataset.lesson}`;drawLoop(0)});
const bonuses=[['100 Common Words','common words'],['100 Real Callsigns','verified real callsigns'],['100 Radio Words','radio vocabulary'],['100 Numbers','numeric head copy'],['100 CW Abbreviations','operating abbreviations'],['QSO Head Copy','progressive exchanges'],['Endless Head Copy','continuous practice']];$('#bonusGrid').innerHTML=bonuses.map(x=>`<article class="bonus"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
['wpm','eff','tone','delay'].forEach(k=>{$(`#${k}Range`).oninput=e=>$(`#${k}Value`).textContent=e.target.value});
$('#buildSessionBtn').onclick=()=>{const selected=[...$('#contentSelect').selectedOptions].map(o=>o.value);timeline=buildCustom({familiarization:$('#modeFam').checked,recognition:$('#modeRec').checked,marathon:$('#modeMar').checked,contents:selected,customText:$('#customText').value,wpm:+$('#wpmRange').value,eff:+$('#effRange').value,tone:+$('#toneRange').value,delay:+$('#delayRange').value,variableRecognition:$('#variableRecognition').checked,duration:+$('#durationSelect').value,seed:$('#seedInput').value});$('#statusLabel').textContent='CUSTOM SESSION';drawLoop(0)};
async function play(limit=null){await playback.play(timeline,{lang:$('#languageSelect').value,gender:$('#voiceSelect').value,tone:+$('#toneRange').value,limit,onTick:(t,a)=>{visual.setAnalyser(a);drawLoop(t)}})}
$('#playBtn').onclick=()=>play();$('#previewBtn').onclick=()=>play(30);$('#stopBtn').onclick=()=>{playback.stop();drawLoop(0)};
$('#wavBtn').onclick=async()=>{const b=await exportWav(timeline,voice,{lang:$('#languageSelect').value,gender:$('#voiceSelect').value,tone:+$('#toneRange').value});download(b,'morse-practice-session.wav')};
$('#mp3Btn').onclick=async()=>{const b=await exportMp3(timeline,voice,{lang:$('#languageSelect').value,gender:$('#voiceSelect').value,tone:+$('#toneRange').value});download(b,'morse-practice-session.mp3')};
$('#metaBtn').onclick=()=>download(new Blob([JSON.stringify({generator:'Morse Practice · CW Studio',author:'ZP5DXS',created:new Date().toISOString(),timeline:timeline.meta,duration:timeline.duration},null,2)],{type:'application/json'}),'morse-practice-metadata.json');
$('#videoBtn').onclick=async()=>{alert('WebM real-time export scaffold is reserved in v1.1. Audio and visuals already share the same timeline, so the exporter can be attached without changing course/session logic.');};
