import {Timeline} from './timeline.js?v=17';import {tokenDuration,wordDuration} from './morse-engine.js?v=17';
const LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ',NUMBERS='0123456789';
const ABBR=['TNX','FER','PSE','AGN','FB','GM','GA','GE','WX','ANT','RIG'],CALLS=['ZP5DXS','W1AW','K1ABC','LU1ABC','PY2XYZ','JA1ABC','DL4ABC','EA7XYZ'];
const PROSIGNS=['BT','AR','SK','KN'],PUNCT=['?','/'];
function rng(seed){let x=0;for(const c of seed)x=(x*31+c.charCodeAt(0))>>>0;return()=>((x=(1664525*x+1013904223)>>>0)/4294967296)}
export function buildCustom(o){const tl=new Timeline({kind:'custom',title:'CW Studio Session',options:o});let t=0,r=rng(o.seed||'MP');tl.add('title',0,4,{title:o.lang==='es'?'SESIÓN DE PRÁCTICA CW':'CW PRACTICE SESSION',subtitle:`${o.wpm} WPM`,blankVisual:true});t=4;const pools=[];for(const c of o.contents){if(c==='letters')pools.push(...LETTERS);if(c==='numbers')pools.push(...NUMBERS);if(c==='alnum')pools.push(...(LETTERS+NUMBERS));if(c==='punctuation')pools.push(...PUNCT);if(c==='prosigns')pools.push(...PROSIGNS);if(c==='abbreviations')pools.push(...ABBR);if(c==='callsigns')pools.push(...CALLS);if(c==='prefixes')pools.push('ZP','LU','PY','K','W','JA','DL','EA');if(c==='rst')pools.push('599','579','559','589');if(c==='qso')pools.push('CQ CQ DE ZP5DXS ZP5DXS K','TNX FER QSO 73 SK');if(c==='words')pools.push('RADIO','ANT','POWER','SIGNAL','RIG','NAME','QTH');if(c==='custom'&&o.customText)pools.push(...o.customText.toUpperCase().split(/\s+/).filter(Boolean))}if(!pools.length)pools.push(...LETTERS);
  if(o.familiarization){const fam=pools.filter(x=>x.length===1&&/[A-Z0-9]/.test(x)).slice(0,36);for(const item of fam){const d=tokenDuration(item,o.wpm);tl.add('cw',t,d,{text:item,wpm:o.wpm,eff:o.eff,mode:'familiarization',mnemonic:true});t+=d+.4;tl.add('reveal',t,1,{text:item,mnemonic:true,lang:o.lang||'es'});t+=1.1;tl.add('charVoice',t,.7,{char:item});t+=.9;tl.add('cw',t,d,{text:item,wpm:o.wpm,eff:o.eff});t+=d+.9}}
  const end=Number(o.duration||900);while(t<end-8){const item=pools[Math.floor(r()*pools.length)],itemTone=o.toneVariation?Math.round((o.tone+(r()-.5)*120)/10)*10:o.tone;if(o.recognition){if(o.variableRecognition&&item.length===1){const speeds=[Math.max(8,o.wpm-3),o.wpm,o.wpm+3];for(const s of speeds){const d=tokenDuration(item,s);tl.add('cw',t,d,{text:item,wpm:s,eff:s,tone:itemTone,mode:'recognition'});t+=d+.25}}else{const d=wordDuration(item,o.wpm,o.eff);tl.add('cw',t,d,{text:item,wpm:o.wpm,eff:o.eff,tone:itemTone,mode:'recognition'});t+=d}t+=o.delay;tl.add('reveal',t,.8,{text:item});t+=1}else if(o.marathon){const d=wordDuration(item,o.wpm,o.eff);tl.add('cw',t,d,{text:item,wpm:o.wpm,eff:o.eff,tone:itemTone,mode:'marathon'});t+=d+.3}else break}
  tl.add('outro',t,5,{title:o.lang==='es'?'SESIÓN COMPLETADA':'SESSION COMPLETE'});tl.duration=t+5;return tl.sort()}
